SELECT P.PRODUCT_CODE, SUM(OS.SALES_AMOUNT * P.PRICE) AS SALES FROM PRODUCT P
INNER JOIN OFFLINE_SALE OS ON P.PRODUCT_ID = OS.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC, P.PRODUCT_CODE;

# SELECT P.PRODUCT_CODE, OS.PRODUCT_ID, SUM(SALES_AMOUNT), P.PRICE, SUM(SALES_AMOUNT) * PRICE AS SUM_PRICE  FROM OFFLINE_SALE OS
# INNER JOIN PRODUCT P ON OS.PRODUCT_ID = P.PRODUCT_ID
# GROUP BY OS.PRODUCT_ID
# ORDER BY P.PRODUCT_CODE DESC;