WITH RECURSIVE ECOLIS AS(
    SELECT ID, PARENT_ID, SIZE_OF_COLONY, DIFFERENTIATION_DATE, GENOTYPE, 1 AS DEPTH FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT ED.ID, ED.PARENT_ID, ED.SIZE_OF_COLONY, ED.DIFFERENTIATION_DATE, 
        ED.GENOTYPE, ES.DEPTH+1 AS DEPTH FROM ECOLI_DATA ED
    JOIN ECOLIS ES ON ES.ID = ED.PARENT_ID
)
SELECT ID FROM ECOLIS
WHERE DEPTH = 3
ORDER BY ID;
