SELECT ID,
    CASE
        WHEN PERCENT = 25 THEN 'CRITICAL'
        WHEN PERCENT = 50 THEN 'HIGH'
        WHEN PERCENT = 75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM (
    SELECT ID, SIZE_OF_COLONY,
    (NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) * 25) AS PERCENT
    FROM ECOLI_DATA
) AS TEMP
ORDER BY ID ASC;
