SELECT I2.ITEM_ID, I2.ITEM_NAME, I2.RARITY FROM ITEM_TREE T
JOIN ITEM_INFO I1 ON T.PARENT_ITEM_ID = I1.ITEM_ID
JOIN ITEM_INFO I2 ON T.ITEM_ID = I2.ITEM_ID
WHERE I1.RARITY = 'RARE'
ORDER BY I2.ITEM_ID DESC;